sudo: false
language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 'iojs'
before_install:
  - "mkdir -p ~/.npm"
install:
  - npm install
  - npm install git://github.com/hybridgroup/cylon.git
  - npm install -g jshint istanbul codeclimate-test-reporter
script:
  - make ci
  - CODECLIMATE_REPO_TOKEN=3b709cfa24296b831e9bec667aa55eea85cbeb4f21ba08f795483aa3a846ee8e codeclimate-test-reporter < coverage/lcov.info
